export * from './types';
export { Fragment } from './components/Fragment';
export { Portal } from './components/Portal';
export { classnames, stylesheet } from './components/xml.attrs';
export { useActionState } from './hooks/useActionState';
export { useCallback } from './hooks/useCallback';
export { useContext } from './hooks/useContext';
export { useDebugValue } from './hooks/useDebugValue';
export { useDeferredValue } from './hooks/useDeferredValue';
export { useEffect } from './hooks/useEffect';
export { useId } from './hooks/useId';
export { useImperativeHandle } from './hooks/useImperativeHandle';
export { useInsertionEffect } from './hooks/useInsertionEffect';
export { useLayoutEffect } from './hooks/useLayoutEffect';
export { useMemo } from './hooks/useMemo';
export { useOptimistic } from './hooks/useOptimistic';
export { useReducer } from './hooks/useReducer';
export { useRef } from './hooks/useRef';
export { useState } from './hooks/useState';
export { useSyncExternalStore } from './hooks/useSyncExternalStore';
export { useTransition } from './hooks/useTransition';
export { cache } from './cache';
export { createContext } from './createContext';
export { memo } from './memo';
export { getContext as use } from './use';
import { VNode } from './VNode';
import { JSXNode } from './JSXNode';
import { FC, Props, Context, ComponentChildren, JSX } from './types';
declare function createElement<P extends Props>(type: FC<P>, props?: null | P, ...children: ComponentChildren[]): JSXNode;
declare function createElement<C>(type: Context<C>, props?: null | {
    value: C;
    children?: ComponentChildren;
}, ...children: ComponentChildren[]): JSXNode;
declare function createElement<E extends keyof JSX.IntrinsicElements>(type: E, props?: null | JSX.IntrinsicElements[E], ...children: ComponentChildren[]): JSXNode;
export { createElement };
export declare function render(children: any, domNode: HTMLElement | SVGElement): VNode;
export declare function createRoot(domNode: HTMLElement | SVGElement): {
    render(children: any): VNode;
};
